stages:
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH # Only commit or merge


###     DEPLOY      ###
"Deploy":
  stage: deploy
  tags:
    - "deploy"
  environment: DEV
  image: "instrumentisto/rsync-ssh:alpine3.16"
  variables:
    SSH_CONNECT: "deploy@wordpress.dev.idsk.skit.zone"
  before_script:
    - apk add --update bash
  script:
    - bash -xc "source ./ci/lib-deploy.sh; deploy_project ./ /srv/wordpress/plugins/${CI_PROJECT_NAME}"
  only:
    - develop
    - /^devops\/.*$/
